apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: beneficial-armadillo-java-springboot
  janus-idp.io/tekton: beneficial-armadillo-java-springboot
  backstage.io/kubernetes-id: beneficial-armadillo-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: beneficial-armadillo-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
